src/Tsi.Template.Web/Controllers/DepartementController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tsi.Template.Abstraction.Common;
using Tsi.Template.Abstraction.Grh;
using Tsi.Template.Domain.Defaults;
using Tsi.Template.Helpers.grh;
using Tsi.Template.ViewModels.Grh;
using Tsi.Template.Web.Factories.Grh;

namespace Tsi.Template.Web.Controllers
{

    [Authorize]
    public class DepartementController : TsiBaseController
    {
        private readonly IDepartmentService _departmentService;
        private readonly IDepartementModelFactory _departementModelFactory;
        private readonly IPermissionService _permissionService;

        public DepartementController(IDepartmentService DepartmentService, IDepartementModelFactory DepartementModelFactory, IPermissionService permissionService)
        {
            _departmentService = DepartmentService;
            _departementModelFactory = DepartementModelFactory;
            _permissionService = permissionService;
        }
        public async Task<IActionResult> IndexAsync()
        {
            var departments = await _departmentService.GetAllAsync();

            return View(departments.ToViewModels());
        }

        public async Task<IActionResult> Create()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageDepartements))
            {
                return Check();
            }

            var model = await _departementModelFactory.PrepareDepartementViewModelAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(DepartementViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var departement = model.ToDepartement();

            await _departmentService.CreateDepartementAsync(departement);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("Departement/Edit/{id}")]
        public async Task<IActionResult> EditAsync(int id) => View((await _departmentService.GetDepartementbyId(id)).ToViewModel());


        [HttpPost]
        public async Task<IActionResult> EditAsync(DepartementViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            await _departmentService.UpdateDepartementAsync(model);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet("Departement/Delete/{id}")]
        public async Task<IActionResult> DeleteAsync(int id)
        {
            await _departmentService.DeleteDepartementAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

src/Tsi.Template.Web/Views/Departement/Create.cshtml
@using Tsi.Template.ViewModels.Grh;
@using Tsi.Template.Core.Enums;
@model DepartementViewModel


@section leftSideBar
{
    @await Component.InvokeAsync("Sidebar", new { selectedTab = NavigationItems.Grh | NavigationItems.Departement })
}


<div class="card">
    <div class="card-body">
        <h5 class="card-title">Create Departement</h5>
        <form asp-controller="Departement" asp-action="Create" method="post">

            <div class="form-group">
                @Html.DisplayNameFor(model => model.Code)
                <input type="text" id="Code" name="Code" class="form-control" value="@Model.Code" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.Libelle)
                <input type="text" id="Libelle" name="Libelle" class="form-control" value="@Model.Libelle" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>


            <div class="form-group text-center">
                <button type="submit" name="save" class="btn btn-primary col-md-3">
                    <i class="far fa-save"></i> Save
                </button>
            </div>
        </form>
    </div>
</div>

src/Tsi.Template.Web/Views/Departement/Edit.cshtml
@using Tsi.Template.ViewModels.Grh;
@using Tsi.Template.Core.Enums;
@model DepartementViewModel


@section leftSideBar
{
    @await Component.InvokeAsync("Sidebar", new { selectedTab = NavigationItems.Grh | NavigationItems.Departement })
}

<div class="card">
    <div class="card-body">
        <h5 class="card-title">Edit Departement</h5>
        <form asp-controller="Departement" asp-action="Edit" method="post">

            <div class="form-group">
                @Html.DisplayNameFor(model => model.Code)
                <input type="text" id="Code" name="Code" class="form-control" value="@Model.Code" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.DisplayNameFor(model => model.Libelle)
                <input type="text" id="Libelle" name="Libelle" class="form-control" value="@Model.Libelle" />
                <span asp-validation-for="Libelle" class="text-danger"></span>
            </div>


            <div class="form-group text-center">
                <button type="submit" name="save" class="btn btn-primary col-md-3">
                    <i class="far fa-save"></i> Save
                </button>
            </div>
        </form>
    </div>
</div>

src/Tsi.Template.Web/Views/Departement/Index.cshtml
@using Tsi.Template.ViewModels.Grh;
@using Tsi.Template.Core.Enums;
@model IEnumerable<DepartementViewModel>


@section leftSideBar
{
    @await Component.InvokeAsync("Sidebar", new { selectedTab = NavigationItems.Grh | NavigationItems.Departement })
}


<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            <div class="cards-group">
                <div>
                    <h2>Departement List</h2>
                    <div class="icon-search">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Departement" asp-action="Create">
                            <i class="fas fa-plus-circle"></i>Create
                        </a>
                    </div>

                </div>

                <br />

                <div class="card card-default">
                    <div class="card-body">

                        <table class="table">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Code</th>
                                    <th scope="col">Libelle</th>

                                    <th scope="col" colspan="2">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ int index = 0;}
                                @foreach (DepartementViewModel item in Model)
                                {
                                    index++;
                                    <tr>
                                        <th scope="row">@index</th>
                                        <td>@item.Code</td>
                                        <td>@item.Libelle</td>

                                        <td>
                                            @Html.ActionLink("Delete", "Delete", "Departement", new { id = item.Id }, null)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", "Departement", item, null)
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br />



</section>